# Site settings
title:       Andrew Hoskins
email:       arhoskin@ualberta.ca
author:      Andrew Hoskins
description: Hi, I'm Andrew.  I’m a Computer Engineering student at the University of Alberta in Edmonton. Currently, I’m an intern on the ANT+ team at Dynastream Innovations in lovely Cochrane, Alberta.
baseurl:     ""
url:         "http://www.andrewhoskins.ca"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: ahoskins
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
